name: train_dist_figure_extraction
desc: Script for training the figure extraction model (Distributed Data Parallel)
cmd: >
  python3 train.py
  --dataset ${segmentation}/segmentation
  --omodel ${OUTPUT_MODEL}
  --params ${PARAMS}
env:
  #docker:
    #image: cr.yandex/crp9dqvp603lodovpio2/pytorch:2.3.0-cuda12.1-cudnn8-devel_1
    #username: oauth
    #password:
      #secret-id: container
  python:
    type: manual
    version: 3.10.14
    requirements-file: ../../requirements.txt
    local-paths:
      - train.py
      - worker.py
      - ../../animator
datasets:
  - bt10b01jjnrqghp5hgbk: segmentation
inputs:
  - hyperparameters.yaml: PARAMS
outputs:
  - train_checkpoints/train_checkpoints.zip: OUTPUT_MODEL
cloud-instance-type: g1.2