name: train_dist_figure_extraction
desc: Script for training the figure extraction model (Distributed Data Parallel)
cmd: python3 -m train_eval.figure_extraction.train --dataset ${segmentation}/segmentation --prhome ${DS_PROJECT_HOME} --omodel ${RES_MODEL}
env:
  #docker:
    #image: cr.yandex/crp9dqvp603lodovpio2/pytorch:2.3.0-cuda12.1-cudnn8-devel_1
    #username: oauth
    #password:
      #secret-id: container
  python:
    type: manual
    version: 3.10.14
    requirements-file: requirements.txt
datasets:
  - bt10b01jjnrqghp5hgbk: segmentation
outputs:
  - train_checkpoints/train_checkpoints.zip: RES_MODEL
flags:
  - attach-project-disk 
cloud-instance-type: gt4.1