name: train_dist_figure_extraction
desc: Script for training the figure extraction model (Distributed Data Parallel)
cmd: >
  python3 train.py
  --dataset ${SEGMENTATION}/segmentation
  --omodel ${OUTPUT_MODEL}
  --imodel ${IMODEL}
  --params ${PARAMS}
  --st ${RES_STORAGE}
env:
  #docker:
    #image: cr.yandex/crp9dqvp603lodovpio2/torch:2.3.1_1
    #username: oauth
    #password:
      #secret-id: container
  python:
    type: manual
    version: 3.10.14
    requirements-file: ../../requirements.txt
    local-paths:
      - train.py
      - worker.py
      - ../../animator
datasets:
  - bt10b01jjnrqghp5hgbk: SEGMENTATION
s3-mounts:
  - bt11r1gu4mqn42erca1d: RES_STORAGE
inputs:
  - train_checkpoints/2024_06_17_16_30_05/69.pt: IMODEL
  - hyperparameters.yaml: PARAMS
outputs:
  - train_checkpoints: OUTPUT_MODEL
cloud-instance-type: g1.2