main: 
  random_state: 10
  batch_size: 64
  epochs: 2

data:
  data_part: 0.9 # Proportions to split data for train and evaluation
  sub_part_data: 1.0 # Part of picked data to use for training (useful for project tests, for real training process set == 1)
  size: [224, 224]
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

distributed:
  world_size: 2  # Number of GPU/CPU
  # Initialization the default distributed process group
  backend: 'nccl' # 'nccl' -- for GPU, 'gloo' for CPU
  port: '12345'
  address: 'localhost'

optimizers:
  lr: 0.001
  betas: [0.9, 0.999]    

model:
  mtype: 'UNet' # UNet or SegNet
  marchitecture: 'B' # A, B, or C. Ditails in unet_mode.py and segnet_model.py 

metrics:
  threshhold: 0.1 # Threshold for Jaccardmetric