name: train_dist_style_transfer
desc: Script for training the cycleGAN model (Distributed Data Parallel)
cmd: >
  python3 train.py
  --dataset ${TRANSFORM}/transfer_test/
  --omodel ${OUTPUT_MODEL}
  --imodel ${IMODEL}
  --params ${PARAMS}
  --st ${RES_STORAGE}
env:
  python:
    type: manual
    version: 3.10.14
    requirements-file: ../../requirements.txt
    local-paths:
      - train.py
      - worker.py
      - ../../animator
datasets:
  - bt12nq8hucmb8tgocl1n: TRANSFORM
s3-mounts:
  - bt1osbecqjrq62ucvoec: RES_STORAGE
inputs:
  - train_checkpoints/29.pt: IMODEL
  - hyperparameters.yaml: PARAMS
outputs:
  - train_checkpoints: OUTPUT_MODEL
cloud-instance-type: g1.2